{
	"name":"ShoppingSettleAccounts",
	"description":"购物结账",
	"version":"1",
	
	"params":[{
		"name":"shoppingCarId",
		"description":"购物车id",
		"scope":1,
		"dataType":"string",
		"required":true
	}],
	
	// 事件配置
	"events":[{
		"type":1,
		"name":"获取商品",
		"description":"根据购物车id查询到对应的商品",
		"actions":[{
			"type":"sql_query",
			"content":{
				"name":"queryProductsByShoppingCarId",
				"params":[{
					"name":"shoppingCarId",
					"scope":1
				}]
			},
			"result":{
				"name":"products",
				"scope":4,
				"dataType":"list"
			}
		}]
	}],
	
	"sqls":[{
		"type":4,
		"name":"queryProductsByShoppingCarId",
		"params":[{
			"name":"shoppingCarId",
			"description":"购物车id",
			"scope":5,
			"dataType":"string",
			"required":true
		}],
		"content":{
			"selects":[{
				"result"
			}]
		}
	}]
}